export const ADD_ASSESSMENT_REQUEST = 'ADD_ASSESSMENT_REQUEST'
export const ADD_ASSESSMENT_SUCCESS = 'ADD_ASSESSMENT_SUCCESS'
export const ADD_ASSESSMENT_FAILURE = 'ADD_ASSESSMENT_FAILURE'


export const GET_ASSESSMENT_QUESTIONS_REQUEST = 'GET_ASSESSMENT_QUESTIONS_REQUEST';
export const GET_ASSESSMENT_QUESTIONS_SUCCESS = 'GET_ASSESSMENT_QUESTIONS_SUCCESS';
export const GET_ASSESSMENT_QUESTIONS_FAILURE = 'GET_ASSESSMENT_QUESTIONS_FAILURE';