// // Blog Creation
// export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
// export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
// export const BLOG_CREATE_FAILURE = "BLOG_CREATE_FAILURE";

// // (Optional) Keep update constants if you plan to update blogs later
// export const BLOG_UPDATE_CONTENT_REQUEST = "BLOG_UPDATE_CONTENT_REQUEST";
// export const BLOG_UPDATE_CONTENT_SUCCESS = "BLOG_UPDATE_CONTENT_SUCCESS";
// export const BLOG_UPDATE_CONTENT_FAILURE = "BLOG_UPDATE_CONTENT_FAILURE";


export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_FAILURE = "BLOG_CREATE_FAILURE";

export const BLOG_EDIT_REQUEST = "BLOG_EDIT_REQUEST";
export const BLOG_EDIT_SUCCESS = "BLOG_EDIT_SUCCESS";
export const BLOG_EDIT_FAILURE = "BLOG_EDIT_FAILURE";

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAILURE = "BLOG_DELETE_FAILURE";

export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAILURE = "BLOG_LIST_FAILURE";
