export const SCHEDULE_CLASS_REQUEST = "SCHEDULE_CLASS_REQUEST";
export const SCHEDULE_CLASS_SUCCESS = "SCHEDULE_CLASS_SUCCESS";
export const SCHEDULE_CLASS_FAILURE = "SCHEDULE_CLASS_FAILURE";


export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';