export const GET_ENTERPRISE_LEADS_REQUEST = "GET_ENTERPRISE_LEADS_REQUEST";
export const GET_ENTERPRISE_LEADS_SUCCESS = "GET_ENTERPRISE_LEADS_SUCCESS";
export const GET_ENTERPRISE_LEADS_FAILURE = "GET_ENTERPRISE_LEADS_FAILURE";
