// actionTypes.js

export const SAVE_FORM_DATA_REQUEST = 'SAVE_FORM_DATA_REQUEST';
export const SAVE_FORM_DATA_SUCCESS = 'SAVE_FORM_DATA_SUCCESS';
export const SAVE_FORM_DATA_FAILURE = 'SAVE_FORM_DATA_FAILURE';

export const GET_ALL_FORM_DATA_REQUEST = 'GET_ALL_FORM_DATA_REQUEST';
export const GET_ALL_FORM_DATA_SUCCESS = 'GET_ALL_FORM_DATA_SUCCESS';
export const GET_ALL_FORM_DATA_FAILURE = 'GET_ALL_FORM_DATA_FAILURE';
